package main

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/Laurent00TT/slimproxy/credentials"
	"github.com/Laurent00TT/slimproxy/fsperm"
)

// initConfig writes a ready-to-run config so the first run needs no
// hand-written YAML.
//
// Generating the file before anything listens is deliberate. api-keys is
// live-reloadable and emptying it unregisters the only inbound auth provider,
// after which every request is accepted — so a config-writing endpoint on a
// running process is one bug away from turning live OAuth subscriptions into an
// open relay. Nothing here is exposed over the network.
func initConfig(path, authDir string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("%s already exists (pass -force to overwrite)", path)
	}

	apiKey, err := randomKey()
	if err != nil {
		return fmt.Errorf("generate api key: %w", err)
	}

	if authDir == "" {
		authDir = "auths"
	}
	abs, err := filepath.Abs(authDir)
	if err != nil {
		return fmt.Errorf("resolve auth dir: %w", err)
	}
	if err = os.MkdirAll(abs, 0o700); err != nil {
		return fmt.Errorf("create auth dir: %w", err)
	}
	// Set before any credential lands in it, so what is written later inherits
	// the restriction rather than the parent's entries.
	_ = fsperm.Restrict(abs)

	body := fmt.Sprintf(`# Generated by "slimproxy init". Contains secrets -- keep mode 0600.

host: "127.0.0.1"
port: 8317

# Key inbound clients must present. Generated; change it if you like.
api-keys:
  - %q
allow-unauthenticated: false

auth-dir: %q
proxy-url: ""

# request-retry is the OUTER attempt cap. At 0 the cooldown-aware retry loop is
# skipped entirely -- CLIProxyAPI itself ships no default here.
request-retry: 3
max-retry-interval: 30
max-retry-credentials: 0

debug: false
# request-log writes request AND response bodies verbatim. Redaction only
# covers header names containing authorization, api-key, apikey, token or
# secret -- Cookie and everything else is written in the clear. Treat the log
# directory as secret material once you turn this on.
#
# Off means off. Upstream would still force a full dump on any 4xx or 5xx with
# this disabled -- a bare 401 was enough -- so slimproxy closes that path
# itself; see gatedRequestLogger in proxy/requestlog.go.
request-log: false
log-to-file: false

models: []
`, apiKey, abs)

	if err = os.WriteFile(path, []byte(body), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func randomKey() (string, error) {
	raw := make([]byte, 24)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// printNextSteps tells the operator what to do with the file just written.
func printNextSteps(w io.Writer, path, apiKey string) {
	run := "./slimproxy"
	if runtime.GOOS == "windows" {
		run = "slimproxy.exe"
	}
	fmt.Fprintf(w, `已写入 %s

接下来:

  1. 添加一个上游凭据（会打开浏览器完成授权）
       %s auth add claude

     可用的 provider: %s
     凭据落在配置里的 auth-dir，文件监听会自动发现，不需要重启。

  2. 启动
       %s

     在终端里运行会同时打开全屏面板；输出被重定向时自动退回日志模式。

  3. 把客户端指过来
       OpenAI 兼容      http://127.0.0.1:8317/v1
       Anthropic SDK    http://127.0.0.1:8317
       Gemini SDK       http://127.0.0.1:8317
     Bearer %s

想先看配置解析成什么样、而不绑定端口，运行 "%s check"。
遇到问题运行 "%s doctor"。
`, path, run, strings.Join(credentials.ProviderNames(), " / "),
		run, strings.TrimSpace(apiKey), run, run)
}
